### ISSUE TITLE
Cannot install ob Mac

### ISSUE THREAD

**Issue by jomach** [royshil/obs-backgroundremoval#146]
I cannot install this plugin on a mac with obs 29 x64. I copied as instructed and it did not work

**Comment by thomasfredericks** [comment]
I concur. OBS macOS Intel 29.0.2 does not find the latest obs-backgroundremoval even if the installation instructions are followed.

**Comment by cryptotoolslive** [comment]
I am also haveing the same issue with 20.0.2 x64 on MacOS 13.2.

**Comment by UsghuiYz** [comment]
I'm having the same issue. It simply does not show up in the filters list.

**Comment by PhilippeBourque** [comment]
Same here. Thanks

**Comment by dkp** [comment]
@royshil 
OSX Monterey 12.6.3
OBS 29.0.2

I'm assuming the instructions are:
Mac OSX: Unzip obs-backgroundremoval-macosx.zip to /Applications/OBS.app/Contents/. e.g. $ unzip -o obs-backgroundremoval-macosx.zip -d /Applications/OBS.app/Contents/

However, the main github page provides instructions for building the plugin.  I assume this is not necessary??

I do not see the filter in the filters list.

**Comment by VForsmann** [comment]
Same here for me.
Running on ARM M1 Max.
Also tried OBS v28.0.0 - no filter coming up after extracting the .zip as told in instructions.

**Comment by royshil** [comment]
I'm rebuilding the package and plugin as a whole. Already made progressNew version coming out very soonIt will have a .pkg installer instead of the .zipOn Feb 26, 2023, at 12:20 PM, Vitus Forsmann ***@***.***> wrote:﻿
Same here for me.
Running on ARM M1 Max.
Also tried OBS v28.0.0 - no filter coming up after extracting the .zip as told in instructions.

**Comment by pas4gok** [comment]
Similar issue unable to find the plugin after following instructions to unarchive to the folder as mentioned. Running on 2018 MB Pro OBS 29.0.2

**Comment by TheFutonEng** [comment]
This is also not working on M1 Mac running Monterey 12.4.

**Comment by dayojohn19** [comment]
not yet resolved?

**Comment by OBS1227** [comment]
I just downloaded the latest version 0.5.0 Background Remover and installed it via the  installer, but it doesn't show up in OBS 29.2 at all. I did an OBS restart and the same. I had successfully installed it manually in older versions of OBS, but the menus have changed from the older versions of OBS, so I haven't been able to install manually or via the installer for the later versions.

**Comment by umireon** [comment]
@OBS1227  0.5.0 does not support Apple Silicon. I'm working on #152 and the author of this repository is working on #153 to build Apple Silicon build.

**Comment by OBS1227** [comment]
> @OBS1227 0.5.0 does not support Apple Silicon. I'm working on #152 and the author of this repository is working on #153 to build Apple Silicon build.

Thank You[umireon](https://github.com/umireon), but I thought Silicon was different than intel. Is it?

**Comment by umireon** [comment]
@OBS1227 Please follow the instructions below

### Installation on macOS

Choose arm64 if you have Apple Silicon OBS and choose x86_64 if you have Intel OBS.

Apple leaves some bugs on the installer so you have to take the workaround written below.


You must click on the Change Install Location... button.
<img width="732" alt="Screenshot 2023-01-28 at 22 53 04" src="https://user-images.githubusercontent.com/1067855/215270155-9df7521a-995b-43ab-9550-0c23214f9549.png">

You must ensure the Install for me only selected.
<img width="735" alt="Screenshot 2023-01-28 at 22 53 19" src="https://user-images.githubusercontent.com/1067855/215270169-82be0210-075c-4422-98fe-2b4167ec6da7.png">

**Comment by OBS1227** [comment]
> @OBS1227 Please follow the instructions below
> 
> ### Installation on macOS
> Choose arm64 if you have Apple Silicon OBS and choose x86_64 if you have Intel OBS.
> 
> Apple leaves some bugs on the installer so you have to take the workaround written below.
> 
> You must click on the Change Install Location... button. <img alt="Screenshot 2023-01-28 at 22 53 04" width="732" src="https://user-images.githubusercontent.com/1067855/215270155-9df7521a-995b-43ab-9550-0c23214f9549.png">
> 
> You must ensure the Install for me only selected. <img alt="Screenshot 2023-01-28 at 22 53 19" width="735" src="https://user-images.githubusercontent.com/1067855/215270169-82be0210-075c-4422-98fe-2b4167ec6da7.png">

Thank You, but this is what I had done and just tried it again, but it doesn't show up. I've looked in both places too. Any other ideas?

**Comment by OBS1227** [comment]
I was wondering if you can let me know where all the files go so that I could do it manually?  Thanks.

**Comment by umireon** [comment]
@OBS1227 The plugin bundle should reside in `~/Library/Application Support/obs-studio/plugins`.

**Comment by OBS1227** [comment]
> @OBS1227 The plugin bundle should reside in `~/Library/Application Support/obs-studio/plugins`.
Thank You so much for trying to help me, but I am not a programmer, but have learned through tutorials and trying over and over a little bit about installations. This is what BR taught me in trying to use it in old versions. I was proud of myself for doing this, but the file structure of OBS seemed to change in the newer versions of 
OBS. Having said that, I do have that folder in the plugin folder by copying and pasting the BR folder into the "Go To Folder" in the apple menu. It's not in the audio /video filters or the effect filters. Does bundle mean the whole folder after it is unzipped or a certain part of it? Thanks again!

**Comment by OBS1227** [comment]
The latest version 0.5.12.  works!!!! Thank you to yourself, Roy and all those involved with making the installer available!!!!!

**Comment by dkp** [comment]
I really appreciate all the work you've done on this, but I'm new to OBS and I'm missing something about the installation ; (
- I have an intel mac pro running Monterey.
- I downloaded the Universal Package and unzipped it: https://github.com/royshil/obs-backgroundremoval/releases/download/v0.5.1/obs-backgroundremoval-0.5.12-macos-universal.pkg
- I don't see how to invoke the lovely installer you picture. So, I tried putting the unzipped folder in 
- /Applications/OBS.app/Contents (didn't work)
- /Applications/OBS.app/Contents/PlugIns (didn't work)
- /Users/dpat/Library/Application Support/obs-studio/plugins (didn't work)
- /Applications/OBS.app/Contents/ (as per instruction on website)

Obviously, I'm missing something.  Any help would be appreciated.

**Comment by dethpickle** [comment]
I'm here following with the same issues.  I've installed it, I see it in the App Support/../Plugins folder, but it doesn't show. However, looking at the logs:

`15:43:52.038: os_dlopen(/Users/dave/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval->/Users/dave/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval): dlopen(/Users/dave/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval, 0x0101): tried: '/Users/dave/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/dave/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval' (no such file), '/Users/dave/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))`

This suggests I downloaded the wrong version.  But, I'm on an M1 studio.  Sooo... perhaps somehow I have installed the wrong OBS version and so that's why it isn't working?  I can't imagine how I would have done that, but...

`15:43:47.215: CPU Name: Apple M1 Max
15:43:47.215: CPU Speed: 2400MHz
15:43:47.215: Physical Cores: 10, Logical Cores: 10
15:43:47.215: Physical Memory: 32768MB Total
15:43:47.215: OS Name: macOS
15:43:47.216: OS Version: Version 13.2.1 (Build 22D68)
15:43:47.216: Rosetta translation used: true
15:43:47.216: Kernel Version: 22.3.0
15:43:47.216: hotkeys-cocoa: Using layout 'com.apple.keylayout.US'
15:43:47.216: Current Date/Time: 2023-03-10, 15:43:47
15:43:47.216: Browser Hardware Acceleration: true
15:43:47.216: Qt Version: 6.4.1 (runtime), 6.4.1 (compiled)
15:43:47.216: Portable mode: false
15:43:47.396: OBS 29.0.2 (mac)
`

I'm guessing the `Rosetta translation used: true` is confirming I'm not really on a arm64 version of OBS.  I'll go looking for that and come back later.  Btw, I've upgraded at least a couple versions of OBS on this machine.  So perhaps it's through the generations of upgrading OBS that has led me to this point.  I'll look at a fresh install of OBS.

**Comment by dethpickle** [comment]
Yup.  That was it.  Downloaded OBS again and overwrote my install, deleted the background removal plugin from the App Support folder and reinstalled it.  It works.

**Comment by royshil** [comment]
Can we close this issue?

**Comment by dkp** [comment]
It works for me!

**Comment by OBS1227** [comment]
> Can we close this issue?

Yes, Install is a success!!! So other issues that may arise in implementing BR will be started in another issue, correct? Thanks so much for the improvements though.

**Comment by royshil** [comment]
i think we're good to close this issue
