### ISSUE TITLE
Can't apply filter to source mirror

### ISSUE THREAD

**Issue by hatzel** [royshil/obs-backgroundremoval#26]
Hi, not sure if what I was trying is even possible, but I wanted to build a blurred background thing by having the same v4l source once with and once without background removal. (For context, blur filters are, for example, available in streamfx).

Since you can't have two instances of the webcam input with different filters I used source mirrors, but I can't seem to add the background removal filter to a source mirror. The add menu opens up fine, I can name it but after pressing "OK" nothing happens (i.e. no filter appears in the menu, the effect is not applied). I get this output in the log:
```
info: [obs-backgroundremoval] Model input shape 3 x 320 x 320, output shape 2 x 320 x 320
info: User added filter 'Background Removal' (background_removal) to source 'Source Mirror 2'
info: [obs-backgroundremoval] Destroy scalers.
```

I am using the PGBUILD for Arch provided on master (currently commit ab91510832d67235e34eab6ef5feb53be3695d66) and version 27.0.0-1 of the official package on Arch.

On a side note, shouldn't the filter be an effect filter? Not really familiar with OBS but it seems that working the same way as the Chroma Key filter would make sense :)

Really happy that you built this plugin, thanks for putting in the work!

**Comment by ItachiSan** [comment]
The same issue happens on Window, with latest versions of OBS & BG removal.

As the issue author posted, the issues are:

* The filter cannot be applied to a Source Mirror (provided from StreamFX)
* The filter is considered to be an audio filter rather than an effect

As this is the only plugin integrated with OBS and with nice results, it would be great to have it working 😄 
If I can contribute in any way, please let me know.
I know some C/C++ but nothing about OBS plugin creation / hacking.

**Comment by Zahrun** [comment]
Hey, I found a way to use the background removal together with blur background effect:
1. Start webcamoid
2. Go to camera source, select source and resolution
3. Go to preferences and enable virtual camera output
4. In OBS, add V4L2 selecting the webcamoid virtual output
5. You can add two: one with obs-backgroundremoval and the other with StreamFX blur

If you also want to use the OBS virtual camera output:
1. Stop obs
2. Unload v4l2loopback module sudo rmmod v4l2loopback
3. Load it again with two devices sudo modprobe v4l2loopback devices=2
4. Start webcamoid
5. Go to camera source, select source and resolution
6. Go to preferences and enable virtual camera output
7. Make sure the device selected is the second one because OBS will use the first one
8. Uncheck virtual camera box and recheck virtual camera box to apply the change of device
9. In OBS, add V4L2 selecting the webcamoid virtual output
10. You can add two: one with obs-backgroundremoval and the other with StreamFX blur
11. Start Obs virtual camera, it should take the other v4l2loopback device

Good luck!

**Comment by royshil** [comment]
this should now work for other resources than just cameras
