### ISSUE TITLE
Request: RPM package for Fedora and OpenSUSE

### ISSUE THREAD

**Issue by MrDrMcCoy** [royshil/obs-backgroundremoval#290]
**Is your feature request related to a problem? Please describe.**

I have been completely unable to get this plugin to build on either Fedora or OpenSUSE, which are my preferred distributions. 

**Describe the solution you'd like**

An RPM package that would work on Fedora should also work on OpenSUSE, so just the one ought to be fine.

**Describe alternatives you've considered**

I have attempted to follow the build steps for Ubuntu and Arch's PKGBUILD, but the plugin either doesn't build or is borked in OBS. A working set of build instructions for Fedora and/or OpenSUSE would be acceptable short of a real RPM package.

**Comment by umireon** [comment]
We don't have any resources to provide RPM packages.
OBS has no official RPM packages so we are not likely to be going to maintain RPM packages.
Please try FlatPak for Fedora and openSUSE.

We will appreciate your effort to maintain an RPM package, of course!

Thanks in advance!

**Comment by umireon** [comment]
You may want to see the build documentation for openSUSE
https://github.com/royshil/obs-backgroundremoval/pull/291/files

**Comment by aspiers** [comment]
PackMan has [an `obs-studio` package in its `Multimedia` project](http://packman.links2linux.org/package/obs-studio), and also a  [`obs-v4l2sink`](http://packman.links2linux.org/package/obs-v4l2sink) package which demonstrates the viability of hosting obs plugins in that project alongside OBS itself.

So it would be possible to fork that project, add a new `obs-backgroundremoval` package, and optionally submit the new package back to the official `Multimedia` project for ongoing maintenance.

**Comment by umireon** [comment]
@aspiers If you are interested, you can add this plugin on PackMan 😉

**Comment by aspiers** [comment]
I wish I had the time for that! Maybe in the future...

**Comment by royshil** [comment]
What's the process for getting a package on PacMan?

If it's a straightforward thing then I can take a stab at it...

**Comment by aspiers** [comment]
PackMan is an instance of the [Open Build Service](https://openbuildservice.org/) which is nicely documented [here](https://openbuildservice.org/help/manuals/obs-user-guide/).  TBH it's not hugely straightforward (speaking as someone who worked at SUSE and contributed to openSUSE for many years), although it is a very satisfying and useful skill to obtain, because it can solve the problem of building Linux packages for multiple distros ([not just `.rpm` and `.deb` but also Arch, AppImage, FlatPak ...](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.package_formats.html)) from a single place.

The process would be roughly:
1. Install and setup the OBS client (`osc`)
2. Branch the `obs-studio` package from the `Multimedia` on Packman
3. Create a new `obs-backgroundremoval` package
4. Fiddle with the spec file until it builds correctly (either locally via `osc build`, or in Packman)
5. `osc commit` the source files
6. (Optionally) `osc submitreq` to submit a request to have the new plugin package incorporated back into the official `Multimedia` project
7. (Optionally) Similar process to get it building in other formats too

**Comment by umireon** [comment]
It's confusing that the abbreviations of Open Build Service and Open Broadcaster Software are the same as OBS  🤣

**Comment by umireon** [comment]
Can't we just use [openSUSE Build Service](https://build.opensuse.org/) instead of PackMan?

**Comment by umireon** [comment]
@aspiers Can't we just use [openSUSE Build Service](https://build.opensuse.org/) instead of PackMan?

**Comment by aspiers** [comment]
Unlikely because the openSUSE Build Service has license-based constraints on what can be packaged there:

https://en.opensuse.org/openSUSE:Build_Service_application_blacklist#Software_which_is_encumbered_by_patent_claims

Several codecs fall foul of this, which is why PackMan (which doesn't have these constraints) is generally the go-to place for packaging patent-encumbered software for OpenSUSE.

I'm pretty sure this is why you'll only find openSUSE packages for Open Broadcaster Software on PackMan, not on the openSUSE Build Service.

Additionally, just from a pragmatic standpoint, PackMan has already done the heavy lifting to create a workable build environment for the `obs-studio` Open Broadcaster Software package, so I assume that building a plugin within the same environment will be a lot easier.  In particular, it means that the plugin can be built against the same libraries and development files (headers, source etc.) involved in the build of the `obs-studio` package.
