### ISSUE TITLE
Background Removal Installation 

### ISSUE THREAD

**Issue by Roblokey** [royshil/obs-backgroundremoval#411]
When running the Installer exe.
The Background removal plugin installs under the Effects filter, not the Audio/Video filter. How do I change this?

**Comment by umireon** [comment]
This plugin is an effect filter. You cannot change the type of the filter.
Why do you want to change the type of this plugin?

**Comment by Roblokey** [comment]
As an effect filter, it will not allow me to change the background color.

**Comment by umireon** [comment]
You can place a color source behind the source to which this plugin is applied.

In addition, the feature of specifying the background color is intentionally removed because the background color can be provided by the color source.
In contrast to your understanding, the type of this plugin (Effect or Audio/Video) is not related to the removal of this feature.

If you want us to bring back the feature of specifying the background color, can you create another feature requesting issue with some reasonable use cases?

Best,

**Comment by Roblokey** [comment]
I guess I may not be explaining my issue correctly. I understand that the background removal is a filter. Other videos that I have watched show that this plugin, once installed, becomes an option under your Audio/video source as a filter under the Audio/Video filter setting. When I install the plugin it becomes an option under the Effects filter. Thus not allowing me to change my background.

**Comment by umireon** [comment]
Please follow the latest official tutorial video: https://youtu.be/veqNEsMqEE0
All the other videos on the internet are too old and not applicable to the current version.

**Comment by royshil** [comment]
@umireon yes go for it
