### ISSUE TITLE
Changing Camera Resolution Crashes OBS

### ISSUE THREAD

**Issue by MadMartian** [royshil/obs-backgroundremoval#77]
When changing the web cam resolution while the background removal filter is running OBS crashes and the camera resolution setting is lost.  This occurs on at least both Windows 10 and Linux Ubuntu 20.04.

Refer to [this forum post](https://obsproject.com/forum/threads/obs-crash-when-changing-webcam-resolution-logs-included.152275/) for logs.

**Work-around:**
- Disable (make non-visible) the background removal filter
- Change web cam resolution
- Re-enable (make visible) the background removal filter

Additionally, given the above work-around, if the new camera resolution is large enough then after re-enabling the background removal filter the removal filter will appear to be cropped rectangle and will not process the entire camera viewport.  The workaround for this behaviour is to restart OBS.

If anyone is familiar with the code and can point me in the right direction I'd be happy to submit a pull request.

**Comment by royshil** [comment]
You may want to add a check in https://github.com/royshil/obs-backgroundremoval/blob/e707b3a20fe34432ee0cecb35ecea8e24d0c2542/src/background-filter.cpp#L489 to see if the resolution has changed since the last frame - and then invalidate the scalers (the code will pick up on that and create new scalers according to the new resolution). Just call `destroyScalers(tf);`, or https://github.com/royshil/obs-backgroundremoval/blob/e707b3a20fe34432ee0cecb35ecea8e24d0c2542/src/background-filter.cpp#L403 for initializing new scalers

**Comment by royshil** [comment]
this should be resolved in new releases
