### ISSUE TITLE
MODNet for better portrait segmentation trained in AISegmentation dataset

### ISSUE THREAD

**Issue by kapulkin** [royshil/obs-backgroundremoval#81]
I would like to offer MODNet model trained during hackaton on https://www.kaggle.com/laurentmih/aisegmentcom-matting-human-datasets

Hackaton repository with train loop code and kaggle notebook is here: https://github.com/PP22MotionLearning/MODNet

Pretrained weights are here: https://drive.google.com/file/d/1mshivzbkzsb_e97Xf7Y3u-1LKp0hvMkh/view

Result looks pretty good:
![2022-02-20_13-16-07](https://user-images.githubusercontent.com/800129/155370761-280aae37-ffb4-4a3c-8def-d26857306ea8.png)

**Comment by Alvazz** [comment]
Thanks for sharing, but Google Drive can't access, no permission

**Comment by datakurre** [comment]
@kapulkin Would you be able to help torch-onnx-newbie, how to properly convert the weights into onnx format?

I tried with pytorch 1.7.1 and the scripts at https://github.com/ZHKKKe/MODNet/tree/master/onnx  

I got the following warning

> UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
> UserWarning: You are trying to export the model with onnx:Upsample for ONNX opset version 9. This operator might cause results to not match the expected results by PyTorch.
ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
We recommend using opset 11 and above for models using this operator. 
  warnings.warn("You are trying to export the model with " + onnx_op + " for ONNX opset version "

And I think it did not fully work in OBS. Not sure if its because of that conversion or just my setup.

Would you know, if there is an optimal image size for this?

**Comment by datakurre** [comment]
I'd guess this error I get from obs-backgroundremoval is related to the warning that I get during ckpt to onnx conversion

```
error: [obs-backgroundremoval] Exception during initialization: /build/source/onnxruntime/core/providers/cpu/tensor/upsample.h:282 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float>&, onnxruntime::UpsampleMode) const scale >= 1 was false. Scale value should be greater than or equal to 1.
```

**Comment by royshil** [comment]
any resolution regarding the converted ONNX model @datakurre @kapulkin ?

**Comment by erhan-** [comment]
Hey @kapulkin , I am having the same hairy usecase as you :). Will you have a look at the conversion again if you every have time again? That would be really nice! :)

**Comment by royshil** [comment]
Closing stale issue
